-- Activity log for calls and stage changes (v0.2).
--
-- Safe to run more than once: every step checks whether it's already done.
-- Run in the Supabase SQL Editor, copied from this file.

create table if not exists public.lead_activities (
  id bigint generated by default as identity primary key,
  lead_id bigint references public.leads(id) on delete cascade,
  type text not null,        -- call, email, note, stage_change
  outcome text,              -- calls: no_answer, voicemail, spoke, interested, not_interested
  note text,
  created_at timestamptz default now()
);

-- The drawer loads one lead's activity, newest first.
create index if not exists lead_activities_lead_created_idx
  on public.lead_activities (lead_id, created_at desc);

alter table public.lead_activities enable row level security;

-- Signed-in user can read and write activity. (Sign-ups are off, so that's
-- only the owner.)
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'lead_activities'
      and policyname = 'authenticated manage activities'
  ) then
    create policy "authenticated manage activities" on public.lead_activities
      for all to authenticated using (true) with check (true);
  end if;
end
$$;
