-- Demo sites: one personalised concept site per lead, shown to the prospect
-- before a call at /demo/<slug>.
--
-- Safe to run more than once: every step checks whether it's already done.
-- Run in the Supabase SQL Editor, copied from this file.

create table if not exists public.demos (
  id bigint generated by default as identity primary key,
  lead_id bigint not null unique references public.leads(id) on delete cascade,
  template text not null,          -- clearview, brightwater, fifth-street, harlow
  slug text not null unique,       -- readable name plus a random suffix
  overrides jsonb not null default '{}'::jsonb,  -- per-client text edits and hours
  active boolean not null default true,          -- false takes the link down
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text default (auth.jwt() ->> 'email')
);

alter table public.demos enable row level security;

-- Signed-in users manage demos. Prospects never read this table: they go
-- through get_demo below.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'demos'
      and policyname = 'authenticated manage demos'
  ) then
    create policy "authenticated manage demos" on public.demos
      for all to authenticated using (true) with check (true);
  end if;
end
$$;

create or replace function public.demos_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end
$$;

drop trigger if exists demos_touch_updated_at on public.demos;
create trigger demos_touch_updated_at
  before update on public.demos
  for each row execute function public.demos_touch_updated_at();

-- The one door for signed-out visitors: a demo by slug, with only the lead
-- fields a template shows. Returns nothing when the link is switched off or
-- the lead is lost, so those links stop working without an extra step.
-- security definer so anon can read it without any access to leads.
create or replace function public.get_demo(p_slug text)
returns table (
  template text,
  overrides jsonb,
  business_name text,
  dba_name text,
  phone text,
  address text,
  address_2 text,
  city text,
  state text,
  zip text
)
language sql
stable
security definer
set search_path = public
as $$
  select d.template, d.overrides,
         l.business_name, l.dba_name, l.phone,
         l.address, l.address_2, l.city, l.state, l.zip
  from public.demos d
  join public.leads l on l.id = d.lead_id
  where d.slug = p_slug
    and d.active
    and coalesce(l.status, 'new') <> 'lost'
$$;

revoke all on function public.get_demo(text) from public;
grant execute on function public.get_demo(text) to anon, authenticated;
